import Marquee from './components/Marquee';
import Navigation from './components/Navigation';
import Footer from './components/Footer';
import Gtag from './components/Gtag';
import Cookies from './components/Cookies';
import './style/main.sass';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <Marquee />
        <Navigation />
        {children}
        <Footer />
        <Gtag />
        <Cookies />
      </body>
    </html>
  );
}
